apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantya-management
  labels:
    app: plantya-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantya-management
  template:
    metadata:
      name: plantya-management
      labels:
        app: plantya-management
    spec:
      containers:
        - name: plantya-management
          image: registry.digitalocean.com/plantya-registry/plantya-management:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: plantya-management-config-map
            - secretRef:
                name: plantya-management-secret

      