apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plantya-management-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: management.dev.plantya.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plantya-management-service
                port:
                  number: 80