apiVersion: v1
kind: Service
metadata:
  name: plantya-management-service
  namespace: plantya-dev
spec:
  type: ClusterIP
  selector:
    app: plantya-management
  ports:
    - port: 80
      targetPort: 8080
