apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config-map
  namespace: plantya-dev
data:
  quarkus.management.port: 8080

  quarkus.flyway.clean-at-start: false
  quarkus.flyway.migrate-at-start: true
  quarkus.flyway.locations: db/migration

  quarkus.http.cors.enabled: true
  quarkus.http.cors.origins: /.*/
  quarkus.http.cors.methods: GET,POST,PATCH,DELETE,OPTIONS
  quarkus.http.cors.headers: *
  quarkus.http.cors.exposed-headers: *
  quarkus.http.cors.access-control-allow-credentials: true

  quarkus.jackson.property-naming-strategy: SNAKE_CASE

  security.password.argon2.memory: 15360
  security.password.argon2.iterations: 2
  security.password.argon2.parallelism: 1
  security.password.argon2.output-length: 32
  security.password.argon2.type: id

