apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: plantya-dev
spec:
  selector:
    app: user-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  