apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-cluster-management-ingress
  namespace: plantya-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: iot-dev.plantya.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: device-cluster-management-service
                port:
                  number: 80