apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-cluster-management-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: iot-dev.plantya.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: device-cluster-management-service
                port:
                  number: 80