name: Plantya Management CI

on:
  push:
    branches: ["dev"]
    paths:
      - "plantya-management/**"
      - ".github/workflows/ci-plantya-management-dev.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: registry.digitalocean.com/plantya-registry
      IMAGE_TAG: dev

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build & test
        working-directory: plantya-management
        run: mvn -B clean verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DigitalOcean Registry
        run: doctl registry login
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}

      - name: Build & Push Docker image
        working-directory: plantya-management
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
